# Generated by Django 5.1.5 on 2025-04-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0020_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='uid',
        ),
        migrations.DeleteModel(
            name='aregisters',
        ),
        migrations.RemoveField(
            model_name='bookers',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='rbookers',
            name='uid',
        ),
        migrations.DeleteModel(
            name='addcart',
        ),
        migrations.DeleteModel(
            name='bookers',
        ),
        migrations.DeleteModel(
            name='breakfast',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='rbookers',
        ),
        migrations.DeleteModel(
            name='registers',
        ),
    ]
