# Generated by Django 5.1.5 on 2025-04-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0023_aregisters_breakfast_contacts_dinner_lunch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aregisters',
        ),
        migrations.RemoveField(
            model_name='bookers',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='uid',
        ),
        migrations.DeleteModel(
            name='dinner',
        ),
        migrations.DeleteModel(
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='rbookers',
            name='uid',
        ),
        migrations.DeleteModel(
            name='bookers',
        ),
        migrations.DeleteModel(
            name='breakfast',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='rbookers',
        ),
    ]
