# Generated by Django 5.1.5 on 2025-04-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0024_delete_aregisters_remove_bookers_uid_remove_cart_tid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacts',
        ),
    ]
