# Generated by Django 5.1.5 on 2025-04-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0026_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('select', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restoapp.registers')),
            ],
        ),
    ]
