# Generated by Django 5.1.5 on 2025-04-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0027_bookers'),
    ]

    operations = [
        migrations.CreateModel(
            name='rbookers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chein', models.CharField(max_length=255)),
                ('cheout', models.CharField(max_length=255)),
                ('adult', models.CharField(max_length=255)),
                ('child', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('req', models.CharField(max_length=255)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restoapp.registers')),
            ],
        ),
    ]
