# Generated by Django 5.1.5 on 2025-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0028_rbookers'),
    ]

    operations = [
        migrations.CreateModel(
            name='aregisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfname', models.CharField(max_length=255)),
                ('userlname', models.CharField(max_length=255)),
                ('useremail', models.CharField(max_length=255)),
                ('userphone', models.CharField(max_length=255)),
                ('userpassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
