# Generated by Django 5.1.5 on 2025-04-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0031_dinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.CharField(max_length=255)),
                ('quantity', models.CharField(default='', max_length=255)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoapp.breakfast')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoapp.registers')),
            ],
        ),
    ]
