# Generated by Django 5.1.5 on 2025-04-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0035_foodcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoapp.foodcart'),
        ),
    ]
