# Generated by Django 5.1.5 on 2025-04-02 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0037_alter_cart_tid_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbookers',
            name='rid',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='restoapp.rooms'),
            preserve_default=False,
        ),
    ]
