# Generated by Django 5.1.5 on 2025-04-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0038_rbookers_rid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbookers',
            old_name='rid',
            new_name='tid',
        ),
    ]
