# Generated by Django 5.1.5 on 2025-04-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0039_rename_rid_rbookers_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbookers',
            name='tid',
        ),
    ]
