# Generated by Django 5.1.5 on 2025-04-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0043_hcontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hreview',
            name='uid',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='restoapp.registers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='uid',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='restoapp.registers'),
            preserve_default=False,
        ),
    ]
