# Generated by Django 5.1.5 on 2025-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0045_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
